DROP TABLE IF EXISTS `CLAIM`;

CREATE TABLE `CLAIM` (
	`CLAIM_ID`	BIGINT	NOT NULL,
	`CLAIM_TYPE`	INT	NULL,
	`CLAIM_CONTENT`	VARCHAR(2000)	NULL,
	`CLAIM_REIMBURSE`	VARCHAR(5)	NULL,
	`BUSINESS_ID`	BIGINT	NOT NULL,
	`RETAIL_ID`	BIGINT	NOT NULL,
	`DRIVER_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `BUSINESS`;

CREATE TABLE `BUSINESS` (
	`BUSINESS_ID`	BIGINT	NOT NULL,
	`BUSINESS_CODE`	VARCHAR(2000)	NULL,
	`BUSINESS_NAME`	VARCHAR(2000)	NULL,
	`BUSINESS_TEL`	VARCHAR(2000)	NULL,
	`BUSINESS_ADDR`	VARCHAR(2000)	NULL
);

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT` (
	`PRODUCT_ID`	BIGINT	NOT NULL,
	`PRODUCT_TYPE`	INT	NULL,
	`PRODUCT_NAME`	VARCHAR(2000)	NULL,
	`PRODUCT_CODE`	VARCHAR(2000)	NULL,
	`PRODUCT_RECDATE`	TIMESTAMP	NULL,
	`PRODUCT_DEPOSIT_CHK`	VARCHAR(5)	NULL,
	`BUSINESS_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `RETAIL`;

CREATE TABLE `RETAIL` (
	`RETAIL_ID`	BIGINT	NOT NULL,
	`RETAIL_NAME`	VARCHAR(2000)	NULL,
	`CEO`	VARCHAR(2000)	NULL,
	`RETAIL_PUBTEL`	VARCHAR(2000)	NULL,
	`RETAIL_ADDR`	VARCHAR(2000)	NULL
);

DROP TABLE IF EXISTS `DRIVER`;

CREATE TABLE `DRIVER` (
	`DRIVER_ID`	BIGINT	NOT NULL,
	`DRIVER_NAME`	VARCHAR(2000)	NULL,
	`DRIVER_TEL`	VARCHAR(2000)	NULL,
	`DRIVER_ADDR`	VARCHAR(2000)	NULL,
	`DRIVER_SALARY`	INT	NULL,
	`DRIVER_CLSAL`	INT	NULL,
	`RETAIL_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `VOC`;

CREATE TABLE `VOC` (
	`VOC_ID`	BIGINT	NOT NULL,
	`REASON_CHK`	VARCHAR(5)	NULL,
	`VOC_TARGET`	VARCHAR(5)	NULL,
	`VOC_PENALTY`	VARCHAR(2000)	NULL,
	`VOC_REIM`	INT	NULL,
	`DRIVER_CHK`	VARCHAR(5)	NULL,
	`DRIVER_PCHK`	VARCHAR(5)	NULL,
	`DRIVER_DISAGREE`	VARCHAR(5)	NULL,
	`VOC_REGDATE`	TIMESTAMP	NULL,
	`VOC_RECENT`	TIMESTAMP	NULL,
	`EID`	BIGINT	NOT NULL,
	`CLAIM_ID`	BIGINT	NOT NULL,
	`DRIVER_ID`	BIGINT	NOT NULL,
	`RETAIL_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `CS`;

CREATE TABLE `CS` (
	`EID`	BIGINT	NOT NULL,
	`EPART`	INT	NULL,
	`ENAME`	VARCHAR(2000)	NULL,
	`EMAIL`	VARCHAR(2000)	NULL,
	`AFFORD`	VARCHAR(100)	NULL,
	`AT_WORK`	VARCHAR(5)	NULL
);

DROP TABLE IF EXISTS `VOC_HIST`;

CREATE TABLE `VOC_HIST` (
	`HIST_ID`	BIGINT	NOT NULL,
	`HIST_REGDATE`	TIMESTAMP	NULL,
	`VOC_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `REIM`;

CREATE TABLE `REIM` (
	`REIM_ID`	BIGINT	NOT NULL,
	`REIM_DATE`	TIMESTAMP	NULL,
	`VOC_ID`	BIGINT	NOT NULL
);

DROP TABLE IF EXISTS `REVIEW`;

CREATE TABLE `REVIEW` (
	`REVIEW_ID`	BIGINT	NOT NULL,
	`REVIEW_REGDATE`	TIMESTAMP	NULL,
	`VOC_ID`	BIGINT	NOT NULL
);

ALTER TABLE `CLAIM` ADD CONSTRAINT `PK_CLAIM` PRIMARY KEY (
	`CLAIM_ID`
);

ALTER TABLE `BUSINESS` ADD CONSTRAINT `PK_BUSINESS` PRIMARY KEY (
	`BUSINESS_ID`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`PRODUCT_ID`
);

ALTER TABLE `RETAIL` ADD CONSTRAINT `PK_RETAIL` PRIMARY KEY (
	`RETAIL_ID`
);

ALTER TABLE `DRIVER` ADD CONSTRAINT `PK_DRIVER` PRIMARY KEY (
	`DRIVER_ID`
);

ALTER TABLE `VOC` ADD CONSTRAINT `PK_VOC` PRIMARY KEY (
	`VOC_ID`
);

ALTER TABLE `CS` ADD CONSTRAINT `PK_CS` PRIMARY KEY (
	`EID`
);

ALTER TABLE `VOC_HIST` ADD CONSTRAINT `PK_VOC_HIST` PRIMARY KEY (
	`HIST_ID`
);

ALTER TABLE `REIM` ADD CONSTRAINT `PK_REIM` PRIMARY KEY (
	`REIM_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`REVIEW_ID`
);

